services:
  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8091:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo_db
    depends_on:
      - mongo
    networks:
      - app-network

  product_db:
    image: bitnami/postgresql:latest
    container_name: product_db
    ports:
      - "5401:5432"
    environment:
      POSTGRESQL_DATABASE: product_db
      POSTGRESQL_USERNAME: ${PRODUCT_DB_USERNAME}
      POSTGRESQL_PASSWORD: ${PRODUCT_DB_PASSWORD}
    networks:
      - app-network
    volumes:
      - product-db-data:/bitnami/postgresql
      - tmp1:/docker-entrypoint-initdb.d
      - tmp1:/docker-entrypoint-preinitdb.d

  cart_db:
    image: bitnami/postgresql:latest
    container_name: cart_db
    ports:
      - "5402:5432"
    environment:
      POSTGRESQL_DATABASE: cart_db
      POSTGRESQL_USERNAME: ${CART_DB_USERNAME}
      POSTGRESQL_PASSWORD: ${CART_DB_PASSWORD}
    networks:
      - app-network
    volumes:
      - cart-db-data:/bitnami/postgresql
      - tmp1:/docker-entrypoint-initdb.d
      - tmp1:/docker-entrypoint-preinitdb.d

  order_db:
    image: bitnami/postgresql:latest
    container_name: order_db
    ports:
      - "5403:5432"
    environment:
      POSTGRESQL_DATABASE: order_db
      POSTGRESQL_USERNAME: ${ORDER_DB_USERNAME}
      POSTGRESQL_PASSWORD: ${ORDER_DB_PASSWORD}
    networks:
      - app-network
    volumes:
      - order-db-data:/bitnami/postgresql
      - tmp1:/docker-entrypoint-initdb.d
      - tmp1:/docker-entrypoint-preinitdb.d

  payment_db:
    image: bitnami/postgresql:latest
    container_name: payment_db
    ports:
      - "5404:5432"
    environment:
      POSTGRESQL_DATABASE: payment_db
      POSTGRESQL_USERNAME: ${PAYMENT_DB_USERNAME}
      POSTGRESQL_PASSWORD: ${PAYMENT_DB_PASSWORD}
    networks:
      - app-network
    volumes:
      - payment-db-data:/bitnami/postgresql
      - tmp1:/docker-entrypoint-initdb.d
      - tmp1:/docker-entrypoint-preinitdb.d

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  mongo-config:
  product-db-data:
  cart-db-data:
  order-db-data:
  payment-db-data:
  tmp1:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs