server:
  port: 8081

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: user_db
      username: ${MONGO_USERNAME:mongo-username}
      password: ${MONGO_PASSWORD:mongo-password}
      authentication-database: admin
  application:
    name: user-service
