server:
  port: 8083

spring:
  application:
    name: shopping-cart-service
  datasource:
    url: jdbc:postgresql://${CART_DB_HOST:localhost}:${CART_DB_PORT:5402}/cart_db
    username: ${CART_DB_USERNAME:cart-db-username}
    password: ${CART_DB_PASSWORD:cart-db-password}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
