server:
  port: 8082

spring:
  application:
    name: product-catalog-service
  datasource:
    url: jdbc:postgresql://${PRODUCT_DB_HOST:localhost}:${PRODUCT_DB_PORT:5401}/product_db
    username: ${PRODUCT_DB_USERNAME:product-db-username}
    password: ${PRODUCT_DB_PASSWORD:product-db-password}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
